### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by tshafer** [wardrobecms/core-archived#28] opened 2013-08-29 04:25 UTC
I get the error when trying to install the core.

http://paste.laravel.com/Mxg

**Comment by Garbee** [comment] 2013-09-01 21:53
I am unable to reproduce this on a fresh install. Is it still any issue for anyone else?

**Comment by ericlbarnes** [comment] 2013-09-01 23:52
Maybe composer was having issues when @tshafer was installing? I haven't seen this before either.

**Comment by Garbee** [comment] 2013-09-06 12:19
I just tested installing base laravel and adding wardrobe-core to the composer and installing, so it is working fine as of now.

**Comment by ericlbarnes** [comment] 2013-09-06 12:21
Thanks for the follow up. I'm going to close this but if you still have an issue @tshafer just let us know.

**Closed as completed by ericlbarnes** 2013-09-06 12:21 UTC
